---
postgresql_databases:
  - name: '{{ database }}'
    lc_collate: C # defaults to 'en_US.UTF-8'
    lc_ctype: C # defaults to 'en_US.UTF-8'
    #encoding: LATIN1 # defaults to 'UTF-8'
    encoding: WIN1252
    owner: '{{ db_user }}'

postgresql_users:
  - name: '{{ db_user }}'
    password: '{{ db_pass }}'
