---
- name: Ensure {{ rpo_path }} dir Exist
  file:
    path: "{{rpo_path}}"
    state: directory
    mode: '0755'
    owner: '{{ user_service }}'
    group: '{{ user_service }}'

- name: Copy RPO File
  copy:
    src: tttm120.rpo
    dest: "{{ rpo_path }}"
    mode: '0775'
    owner: '{{ user_service }}'
    group: '{{ user_service }}'